Repository RAF-SI-2023/Banka-1-Backend, pull requests merged in 2024-06, with the labels that each got.

#300 update build.yaml
  .prow/build.yaml
Labels: size/XS

#301 update build.yaml
  .prow/build.yaml
Labels: size/XS

#302 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/responses/CustomerResponse.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, size/S, approved

#304 Disabled logger
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved

#303 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/M

#305 Update BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS

#306 Dodatan endpoint za front (svi kalitali koji imaju public)
  user-service/src/main/java/rs/edu/raf/banka1/controller/CapitalController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/AllPublicCapitalsDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Capital.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/CapitalRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
Labels: lgtm, approved, size/M

#307 Update README.md
  README.md
Labels: lgtm, approved, size/XS

#310 Update build.yaml
  .prow/build.yaml
Labels: lgtm, approved, size/XS

#311 Bootstrap data - heroj a ne zlocinac
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS

#309 fix finalize contract checker
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/ContractServiceImpl.java
Labels: lgtm, approved, size/XS

#312 Margin accounts
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/GlobalExceptionHandler.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/MarginAccountController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/LegalOrderRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/MarginAccountCreateDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/MarginAccountDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/OrderDto.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/MarginAccountException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/MarginAccountNotFoundException.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/MarginAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/OrderMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/margincalljob/MarginCallMidnightJob.java
  user-service/src/main/java/rs/edu/raf/banka1/margincalljob/MarginCallMidnightTrigger.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarginAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarginTransaction.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarketOrder.java
  user-service/src/main/java/rs/edu/raf/banka1/model/TransactionType.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/MarginAccountRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/MarginTransactionRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/order/CreateOrderRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/scheduler/MarginSummaryScheduler.java
  user-service/src/main/java/rs/edu/raf/banka1/services/MarginAccountService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/MarginTransactionService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarginAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/OrderServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJobTest.java
Labels: lgtm, approved, size/XXL

#313 error handling
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
Labels: lgtm, approved, size/XS

#314 Sprint 9 - bootstrap data fix for prod
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
Labels: lgtm, size/L, approved

#315 update bootstrap
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved

#316 build trigger
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS

#317 KT4 i KT5 test
  README.md
Labels: lgtm, approved, size/XS

#308 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Contract.java
Labels: lgtm, approved, size/M

#320 fix profit controller path variable
  user-service/src/main/java/rs/edu/raf/banka1/controller/ProfitController.java
Labels: lgtm, approved, size/XS

#321 couple fixes
  fetching-service/src/main/java/rs/edu/raf/banka1/mapper/ForexMapper.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/ForexServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, size/S, approved

#322 removed caching for listing
  market-service/src/main/java/rs/edu/raf/banka1/services/ForexServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ListingStockServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
Labels: lgtm, approved, size/M

#324 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, size/XL, approved

#325 Orders don't require bank account number anymore
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/LegalOrderRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/services/BankAccountService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, approved, size/M

#326 Popravljen Margin
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/ContractRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/ContractServiceImpl.java
Labels: lgtm, approved, size/XS

#327 Sprint 9
  market-service/src/main/java/rs/edu/raf/banka1/controller/BankOtcController.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/FrontendOfferDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/MyOfferDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/MyStockDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/OfferDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/listing/BankOTCStock.java
  market-service/src/main/java/rs/edu/raf/banka1/model/listing/MyStock.java
  market-service/src/main/java/rs/edu/raf/banka1/model/offer/MyOffer.java
  market-service/src/main/java/rs/edu/raf/banka1/model/offer/Offer.java
  market-service/src/main/java/rs/edu/raf/banka1/model/offer/OfferStatus.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/BankOTCStockRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/MyOfferRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/MyStockRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/OfferRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/services/otc/BankOtcService.java
Labels: lgtm, size/XL, approved

#329 Sprint 9
  market-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  market-service/src/main/java/rs/edu/raf/banka1/configuration/SpringSecurityConfig.java
  market-service/src/main/java/rs/edu/raf/banka1/controller/BankOtcController.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/FrontendOfferDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/MyOfferDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/MyStockDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/otc/OfferDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/listing/BankOTCStock.java
  market-service/src/main/java/rs/edu/raf/banka1/model/listing/MyStock.java
  market-service/src/main/java/rs/edu/raf/banka1/model/offer/MyOffer.java
  market-service/src/main/java/rs/edu/raf/banka1/model/offer/Offer.java
  market-service/src/main/java/rs/edu/raf/banka1/model/offer/OfferStatus.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/BankOTCStockRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/MyOfferRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/MyStockRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/otc/OfferRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/services/otc/BankOtcService.java
Labels: lgtm, size/L, approved

#328 publicTotal polje u capital/listings
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
Labels: lgtm, approved, size/XS

#331 add bank account to bootstrap data
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, size/S, approved

#330 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/controller/CapitalController.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/ContractRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/ContractServiceImpl.java
Labels: lgtm, approved, size/M

#334 change all capital dto
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/AllPublicCapitalsDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/ContractRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/ContractServiceImpl.java
Labels: lgtm, approved, size/M

#335 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/BankAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CompanyServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/CompanyServiceImplTest.java
Labels: lgtm, size/L, approved

#337 added otc_trade to user service
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/configuration/SpringSecurityConfig.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/otc_trade/BankOtcController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/otc_trade/FrontendOfferDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/otc_trade/MyOfferDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/otc_trade/MyStockDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/otc_trade/OfferDto.java
  user-service/src/main/java/rs/edu/raf/banka1/model/listing/BankOTCStock.java
  user-service/src/main/java/rs/edu/raf/banka1/model/listing/MyStock.java
  user-service/src/main/java/rs/edu/raf/banka1/model/offer/MyOffer.java
  user-service/src/main/java/rs/edu/raf/banka1/model/offer/Offer.java
  user-service/src/main/java/rs/edu/raf/banka1/model/offer/OfferStatus.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/otc_trade/BankOTCStockRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/otc_trade/MyOfferRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/otc_trade/MyStockRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/otc_trade/OfferRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/otc_trade/BankOtcService.java
Labels: lgtm, size/XL, approved

#339 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, size/S, approved

#344 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/M

#340 Sprint 9-redis
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CardServiceImlp.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/PaymentServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
Labels: lgtm, approved, size/M

#343 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, approved, size/XS

#341 Infinite sell forex loop 'fix'
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CustomerMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationTrigger.java
Labels: lgtm, size/S, approved

#342 fix order history for customer
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/OrderRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, approved, size/M

#345 Additional OTC functionality
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/CapitalRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/otc_trade/BankOtcService.java
Labels: lgtm, approved, size/M

#347 RSD bankAcc fix
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CustomerMapper.java
Labels: lgtm, approved, size/XS

#346 Modify otc dto
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/ContractDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/ContractMapper.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/ContractServiceImplTest.java
Labels: lgtm, approved, size/XS

#349 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CustomerMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/responses/CustomerResponse.java
Labels: lgtm, approved, size/XS

#352 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
Labels: lgtm, approved

#350 Fix capital listing endpoint
  user-service/src/main/java/rs/edu/raf/banka1/controller/BankAccountController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/CapitalController.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/CapitalRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
Labels: lgtm, approved, size/M

#351 push margin small fix
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, approved, size/XS

#348 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
Labels: lgtm, approved, size/M

#353 Timestamp null fix
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS

#354 create margin account and show business accounts for customer
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/MarginAccountCreateDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CustomerMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, approved, size/M

#355 refresh of listings added
  market-service/src/main/java/rs/edu/raf/banka1/controller/MarketController.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ForexService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ForexServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/FuturesService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ListingStockService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ListingStockServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  market-service/src/test/java/rs/edu/raf/banka1/services/ForexServiceImplTest.java
Labels: lgtm, size/L, approved

#357 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved

#358 redis correct
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CardServiceImlp.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/PaymentServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
Labels: lgtm, size/S, approved

#361 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/M

#360 fix margin account
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
Labels: lgtm, approved, size/XS

#356 we are rich now!
  market-service/src/test/java/rs/edu/raf/banka1/services/FuturesServiceImplTest.java
  market-service/src/test/java/rs/edu/raf/banka1/services/ListingStockServiceImplTest.java
  market-service/src/test/java/rs/edu/raf/banka1/services/OptionsServiceImplTest.java
Labels: lgtm, approved, size/M

#362 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, size/S, approved

#363 Sprint 9 fix selenium
  fetching-service/Dockerfile
  fetching-service/src/main/java/rs/edu/raf/banka1/services/DriverServiceImpl.java
Labels: lgtm, size/S, approved

#365 added public amount to dto
  user-service/src/main/java/rs/edu/raf/banka1/dtos/otc_trade/MyStockDto.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/otc_trade/BankOtcService.java
Labels: lgtm, approved, size/XS

#366 Sprint 9 fix bootstrap data and transfer service
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
Labels: lgtm, approved, size/M

#368 Sprint 9
  docker-compose.yaml
  docker.compose.yaml
  docker.compose.yaml.example
  docker.compose.yaml.example.prod
  user-service/src/main/resources/application.properties.forinttest
  user-service/src/main/resources/examples/application.properties.example
  user-service/src/test/java/rs/edu/raf/banka1/services/TransferServiceImplTest.java
Labels: lgtm, size/S, approved

#359 order sell fix
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/model/BankAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
Labels: lgtm, size/L, approved

#367 Fix margin with company
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/MarginTransactionService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
Labels: lgtm, size/S, approved

#369 Prokic ruta
  user-service/src/main/java/rs/edu/raf/banka1/controller/otc_trade/BankOtcController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/otc_trade/EditMyStockDto.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/otc_trade/BankOtcService.java
Labels: lgtm, approved, size/M

#370 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/controller/MarginAccountController.java
Labels: lgtm, approved, size/XS

#372 Bootstrap change
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS

#371 Sprint 9 - BankOtcService testovi
  user-service/src/test/java/rs/edu/raf/banka1/services/BankOtcServiceTest.java
Labels: lgtm, size/L, approved

#373 otc tax the buyer
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/ContractServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/ContractServiceImplTest.java
Labels: lgtm, size/S, approved

#376 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationTrigger.java
Labels: lgtm, approved, size/XS

#374 liquidation
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginAccountServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarginAccountServiceImplTest.java
Labels: lgtm, approved, size/M

#375 check for duplicate key
  fetching-service/src/main/java/rs/edu/raf/banka1/services/CurrencyServiceImpl.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/ForexServiceImpl.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/ListingStockServiceImpl.java
  fetching-service/src/test/java/rs/edu/raf/banka1/services/CurrencyServiceUnitTests.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/TransferDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/TransferMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/TransferMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/TransferMapperTest.java
Labels: lgtm, approved, size/M

#377 fix
  user-service/src/main/java/rs/edu/raf/banka1/model/MarginAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/scheduler/MarginSummaryScheduler.java
  user-service/src/main/java/rs/edu/raf/banka1/services/MarginAccountService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImpl.java
Labels: lgtm, size/S, approved

#378 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
Labels: lgtm, size/S, approved
