Repository RAF-SI-2023/Banka-1-Backend, pull requests merged in 2024-04, with the labels that each got.

#180 Fix createBankAccount and endpoints
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/BankAccountController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/CustomerController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/BankAccountDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/BankAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/AccountType.java
  user-service/src/main/java/rs/edu/raf/banka1/model/BankAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Card.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Payment.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Transfer.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/BankAccountRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/CreateBankAccountRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/customer/AccountData.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/customer/CreateCustomerRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/services/BankAccountService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
  user-service/src/main/resources/examples/application.properties.example
  user-service/src/test/java/rs/edu/raf/banka1/services/BankAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CustomerServiceImplTest.java
Labels: lgtm

#184 Payments and transactions
  banka-1.iml
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PaymentController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/RecipientsController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/PaymentDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/PaymentRecipientDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/BankAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/PaymentMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/RecipientMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/BankAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Customer.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Payment.java
  user-service/src/main/java/rs/edu/raf/banka1/model/PaymentRecipient.java
  user-service/src/main/java/rs/edu/raf/banka1/model/TransactionStatus.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/PaymentRecipientRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/PaymentRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/CreateBankAccountRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/CreatePaymentRecipientRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/CreatePaymentRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/services/BankAccountService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/PaymentService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/RecipientsService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/PaymentServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/RecipientsServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/JwtUtil.java
  user-service/src/test/java/rs/edu/raf/banka1/services/BankAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/PaymentServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/RecipientsServiceImplTest.java
Labels: lgtm, size/XXL

#177 Separate employee and customer login routes
  .github/workflows/deploy.yml
  market-service/Dockerfile
  market-service/pom.xml
  market-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  market-service/src/test/resources/listings.json
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/configuration/SpringSecurityConfig.java
  user-service/src/main/java/rs/edu/raf/banka1/configuration/authproviders/CustomAuthProvider.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/AuthenticationController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PaymentController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/RecipientsController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/UserController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/UserFullDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/customer/CreateCustomerDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/customer/CustomerDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/customer/EditCustomerDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/employee/CreateEmployeeDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/employee/EditEmployeeDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/employee/EmployeeDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/BankAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/BusinessAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CurrentAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CustomerMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/EmployeeMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/ForeignCurrencyAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/UserMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Agent.java
  user-service/src/main/java/rs/edu/raf/banka1/model/BusinessAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/CurrentAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Customer.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Employee.java
  user-service/src/main/java/rs/edu/raf/banka1/model/ForeignCurrencyAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Permission.java
  user-service/src/main/java/rs/edu/raf/banka1/model/User.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/EmployeeRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/UserRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/ForeignCurrencyAccountRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/customer/CustomerData.java
  user-service/src/main/java/rs/edu/raf/banka1/responses/CreateUserResponse.java
  user-service/src/main/java/rs/edu/raf/banka1/responses/CustomerResponse.java
  user-service/src/main/java/rs/edu/raf/banka1/responses/ForeignCurrencyAccountResponse.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CustomerService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/EmployeeService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/AuthenticationService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CardServiceImlp.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/UserServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/RandomUtil.java
  user-service/src/test/java/rs/edu/raf/banka1/SearchAndFilterTests.java
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/controller/UserControllerSteps.java
  user-service/src/test/java/rs/edu/raf/banka1/services/BankAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CustomerServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/UserServiceImplTest.java
Labels: size/XXL

#190 Added route for getting customer by JWT
  user-service/src/main/java/rs/edu/raf/banka1/controller/CustomerController.java
Labels: size/S

#192 AccountData kao na frontu za createCustomer()
  user-service/src/main/java/rs/edu/raf/banka1/requests/customer/AccountData.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CustomerServiceImplTest.java
Labels: lgtm, size/S

#193 Remove recipient endpoint
  user-service/src/main/java/rs/edu/raf/banka1/controller/RecipientsController.java
  user-service/src/main/java/rs/edu/raf/banka1/services/RecipientsService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/RecipientsServiceImpl.java
Labels: size/S

#200 Changed resource loading to use classloader
  market-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ExchangeServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
Labels: size/L

#198 Menjacnica
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PaymentController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransferController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/TransferDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/TransferMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/BankAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Currency.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Payment.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Transfer.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/BankAccountRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/TransferRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/CreateTransferRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransferService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/PaymentServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransferServiceImplTest.java
Labels: lgtm, size/XXL

#202 update za app.prop
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/PaymentServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/RecipientsServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
  user-service/src/main/resources/examples/application.properties.example
  user-service/src/test/java/rs/edu/raf/banka1/services/TransferServiceImplTest.java
Labels: lgtm, size/M

#199 Sprint 5 orders
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/configuration/authproviders/CurrentAuth.java
  user-service/src/main/java/rs/edu/raf/banka1/configuration/authproviders/CurrentAuthAspect.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/BankAccountController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/GlobalExceptionHandler.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransactionController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CapitalDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/LimitDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/NewLimitDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/OrderDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/TransactionDto.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/market_service/ListingBaseDto.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/BankAccountNotFoundException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/CapitalNotFoundByBankAccountException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/CapitalNotFoundByCodeException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/CapitalNotFoundByListingIdAndTypeException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/EmployeeNotFoundException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/ForbiddenException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/InvalidCapitalAmountException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/InvalidReservationAmountException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/NotEnoughCapitalAvailableException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/OrderNotFoundByIdException.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/LimitMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/OrderMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/TransactionMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarketOrder.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/CapitalRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/OrderRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/TransactionRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/CreateTransactionRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/requests/order/CreateOrderRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/scheduler/StockSimulationScheduler.java
  user-service/src/main/java/rs/edu/raf/banka1/services/BankAccountService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/EmployeeService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/MarketService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransactionService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarketServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationTrigger.java
  user-service/src/test/java/rs/edu/raf/banka1/SearchAndFilterTests.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CapitalServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/UserServiceImplTest.java
Labels: size/XXL

#209 Stock simulation fix + test
  user-service/src/main/java/rs/edu/raf/banka1/mapper/EmployeeMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/test/java/rs/edu/raf/banka1/services/EmployeeServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJobTest.java
Labels: size/L

#211 ClassLoader in fetching service
  .github/workflows/deploy.yml
  docker.compose.yaml.example.prod
  fetching-service/Dockerfile
  fetching-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/ExchangeServiceImpl.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/ListingStockServiceImpl.java
  fetching-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
  fetching-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
Labels: size/L

#213 Fix orders
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationTrigger.java
  user-service/src/test/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJobTest.java
Labels: size/M

#212 Tests for transfer service, transfer mapper, payment mapper, payment reciepient mapper
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/PaymentMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/RecipientMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/TransferMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransferServiceImplTest.java
Labels: lgtm, size/L

#210 Sprint 5
  docker-compose-test.yaml
  fetching-service/pom.xml
  inittest.sql
  market-service/pom.xml
  market-service/src/test/java/rs/edu/raf/banka1/cucumber/MarketControllerSteps.java
  market-service/src/test/java/rs/edu/raf/banka1/cucumber/SpringIntegrationTest.java
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/employee/EmployeeDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/UserMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Customer.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Employee.java
  user-service/src/main/java/rs/edu/raf/banka1/responses/CustomerResponse.java
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/CucumberIntegrationTest.java
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/SpringIntegrationTest.java
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/controller/UserControllerSteps.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/EmployeeMapperTest.java
  user-service/src/test/resources/features/bank/bank_account_scenario.feature
  user-service/src/test/resources/features/bank/create/create_foreign_account.feature
  user-service/src/test/resources/features/bank/get/get_all_foreign_accounts.feature
  user-service/src/test/resources/features/bank/get/get_foreign_account_by_id.feature
  user-service/src/test/resources/features/customer/customer_whole_scenario.feature
  user-service/src/test/resources/features/employee/employee_whole_scenario.feature
  user-service/src/test/resources/features/loan/get_loan.feature
  user-service/src/test/resources/features/loan/loan_request_scenario.feature
  user-service/src/test/resources/features/order/order_whole_scenario.feature
  user-service/src/test/resources/features/payment/payment_whole_scenario.feature
  user-service/src/test/resources/features/permissions/get/get_permissions_by_id.feature
  user-service/src/test/resources/features/recipients/recipients_whole_scenario.feature
  user-service/src/test/resources/features/transfer/transfer_whole_scenario.feature
  user-service/src/test/resources/features/users/create/activate_account.feature
  user-service/src/test/resources/features/users/create/create_user.feature
  user-service/src/test/resources/features/users/edit/edit_user.feature
  user-service/src/test/resources/features/users/get/get_all_users.feature
  user-service/src/test/resources/features/users/get/get_all_users_filtered.feature
  user-service/src/test/resources/features/users/get/get_certain_user.feature
  user-service/src/test/resources/features/users/get/get_user_by_id.feature
  user-service/src/test/resources/features/users/get/get_user_permissions.feature
  user-service/src/test/resources/features/users/remove/remove_user.feature
Labels: size/XXL

#215 Sprint 5
  user-service/src/test/java/rs/edu/raf/banka1/mappers/BankAccountMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/CapitalMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/CardMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/CompanyMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/CurrentAccountMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/LoanMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/LoanRequestMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/TransactionMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/TransferMapperTest.java
Labels: lgtm, size/XL

#216 Dodati Unit testovi za CurrencyService za addCurrencies, findById i findByAll metode.
  market-service/src/test/java/rs/edu/raf/banka1/services/CurrencyServiceUnitTests.java
Labels: lgtm, size/M

#219 Sprint 5 unit tests
  user-service/src/main/java/rs/edu/raf/banka1/mapper/UserMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/CustomerMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mapper/EmployeeMapperTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/BankAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CustomerServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/EmployeeServiceImplTest.java
Labels: size/XL

#218 more tests Sprint 5
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CapitalDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/LimitMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Employee.java
  user-service/src/main/java/rs/edu/raf/banka1/services/EmployeeService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CapitalServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/EmployeeServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarketServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/OrderServiceImplTest.java
Labels: size/XXL

#201 Dodao uputstvo za pre-commit file
  README.md
  user-service/src/main/java/rs/edu/raf/banka1/mapper/BusinessAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CurrentAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/ForeignCurrencyAccountMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/BusinessAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/CurrentAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/ForeignCurrencyAccount.java
Labels: size/L

#220 mini fix zbog merga
  user-service/src/test/java/rs/edu/raf/banka1/services/EmployeeServiceImplTest.java
Labels: size/M

#222 Testovi za stock service
  market-service/src/test/java/rs/edu/raf/banka1/services/ListingStockServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/PaymentServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/RecipientsServiceImplTest.java
Labels: size/L

#223 add commission to exchange rates
  user-service/src/main/java/rs/edu/raf/banka1/model/Transfer.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
Labels: size/XS

#224 Add seeding exchanges to jococo ignore in market service
  market-service/pom.xml
Labels: lgtm, size/XS

#217 ForexService and OptionsService tests also fixed mapper for exchangeName
  market-service/src/main/java/rs/edu/raf/banka1/mapper/ForexMapper.java
  market-service/src/main/java/rs/edu/raf/banka1/mapper/FutureMapper.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ForexServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
  market-service/src/test/java/rs/edu/raf/banka1/services/ForexServiceImplTest.java
  market-service/src/test/java/rs/edu/raf/banka1/services/ListingStockServiceImplTest.java
  market-service/src/test/java/rs/edu/raf/banka1/services/OptionsServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/mappers/CurrentAccountMapperTest.java
Labels: size/L

#226 Fixed web scraper
  fetching-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/test/java/rs/edu/raf/banka1/services/ListingStockServiceImplTest.java
Labels: size/M

#229 Sprint 5 orders
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/model/DecideOrderResponse.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/EmployeeServiceImplTest.java
Labels: lgtm, size/L

#225 Added tests for future, changed driver to be a service
  fetching-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/DriverService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/DriverServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/test/java/rs/edu/raf/banka1/services/FuturesServiceImplTest.java
  user-service/src/main/resources/application.properties.forinttest
Labels: size/L

#227 testovi za stock service
  market-service/src/main/java/rs/edu/raf/banka1/services/ListingStockServiceImpl.java
  market-service/src/test/java/rs/edu/raf/banka1/services/ListingStockServiceImplTest.java
Labels: size/XL

#235 Sprint 5
  user-service/src/test/resources/features/employee/employee_whole_scenario.feature
  user-service/src/test/resources/features/order/order_whole_scenario.feature
Labels: size/XS

#238 Napravljeno da se salje i Ticker u response-u za /capitals/listings rutu
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CapitalProfitDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/OrderMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Capital.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
Labels: size/S

#239 Fix orders and limit
  user-service/src/main/java/rs/edu/raf/banka1/controller/GlobalExceptionHandler.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/InvalidOrderListingAmountException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/OrderListingNotFoundByIdException.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/OrderServiceImplTest.java
Labels: lgtm, size/L

#240 Add responses for failed menjacnica transfers and update api key for exchange rates
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransferController.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransferService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
  user-service/src/main/resources/examples/application.properties.example
Labels: lgtm, size/S

#241 Added .prow
  .prow/build.yaml
  .prow/fetching-service.yaml
  .prow/market-service.yaml
  .prow/user-service.yaml
  pom.xml
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
Labels: size/L

#243 Adding prow to root
  .prow/build.yaml
  .prow/fetching-service.yaml
  .prow/market-service.yaml
  .prow/user-service.yaml
  pom.xml
  user-service/src/main/java/rs/edu/raf/banka1/controller/GlobalExceptionHandler.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransferController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CapitalProfitDto.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/InvalidOrderListingAmountException.java
  user-service/src/main/java/rs/edu/raf/banka1/exceptions/OrderListingNotFoundByIdException.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/OrderMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Capital.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CapitalService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransferService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/EmployeeServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/main/resources/examples/application.properties.example
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/OrderServiceImplTest.java
Labels: size/L

#244 Changed yamls CI
  .github/workflows/deploy.yml
  .prow/fetching-service.yaml
  .prow/market-service.yaml
  .prow/user-service.yaml
Labels: size/L

#247 Changes PR
  .prow/fetching-service.yaml
  .prow/market-service.yaml
  .prow/user-service.yaml
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
Labels: size/S

#255 Ignored tests
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CapitalServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/OrderServiceImplTest.java
Labels: size/S

#258 Limits
  user-service/src/main/java/rs/edu/raf/banka1/repositories/TransactionRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransactionService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
Labels: lgtm, size/L

#259 Create OWNERS
  OWNERS
Labels: size/XS

#256 @Ignore shouldCreateBankAccount
  docker.compose.yaml.example
  docker.compose.yaml.example.prod
  inittest.sql
  market-service/src/test/resources/features/listing/get/get_all_listing_by_history.feature
  user-service/src/test/java/rs/edu/raf/banka1/services/CapitalServiceImplTest.java
  user-service/src/test/resources/features/order/order_whole_scenario.feature
Labels: lgtm, size/L, approved

#262 Sprint 6 integracioni
  market-service/src/test/java/rs/edu/raf/banka1/cucumber/MarketControllerSteps.java
  market-service/src/test/resources/features/listing/get/get_all_listings_by_type.feature
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CapitalProfitDto.java
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/controller/UserControllerSteps.java
  user-service/src/test/resources/features/customer/customer_whole_scenario.feature
  user-service/src/test/resources/features/employee/employee_whole_scenario.feature
  user-service/src/test/resources/features/recipients/recipients_whole_scenario.feature
Labels: lgtm, size/XL, approved
