Repository RAF-SI-2023/Banka-1-Backend, pull requests merged in 2024-05, with the labels that each got.

#273 Order docker fix
  docker.compose.yaml.example
  docker.compose.yaml.example.prod
  market-service/src/main/resources/examples/application.properties.forinttest
  user-service/src/main/java/rs/edu/raf/banka1/configuration/RetryConfiguration.java
  user-service/src/main/java/rs/edu/raf/banka1/utils/Constants.java
  user-service/src/main/resources/application.properties.forinttest
Labels: lgtm, size/S, approved

#260 Removed tests
  fetching-service/pom.xml
  market-service/pom.xml
  market-service/src/test/resources/features/listing/get/get_all_listings.feature
  market-service/src/test/resources/features/listing/get/get_all_listings_by_type.feature
  user-service/pom.xml
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/SpringIntegrationTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarketServiceImplTest.java
Labels: lgtm, approved, size/M

#275 Test commit
  README.md
Labels: lgtm, approved, size/XS

#280 Sprint 8
  market-service/src/main/java/rs/edu/raf/banka1/controller/CurrencyController.java
  market-service/src/main/java/rs/edu/raf/banka1/controller/MarketController.java
  market-service/src/main/java/rs/edu/raf/banka1/controller/OptionsController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/BankAccountController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/CustomerController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/LoanController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/LoanRequestController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PaymentController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PermissionController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/RecipientsController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransactionController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransferController.java
  user-service/src/main/resources/examples/application.properties.example
Labels: lgtm, size/L, approved

#285 added api for transfer reports
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransferController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/TransfersReportDto.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransferService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransferServiceImpl.java
Labels: lgtm, approved, size/M

#281 Sprint 8
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransactionController.java
  user-service/src/main/java/rs/edu/raf/banka1/services/TransactionService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
Labels: lgtm, approved, size/M

#282 Added tax to selling stocks when user has profit
  inittest.sql
  market-service/src/main/java/rs/edu/raf/banka1/configuration/SwaggerConfiguration.java
  market-service/src/main/java/rs/edu/raf/banka1/controller/CurrencyController.java
  market-service/src/main/java/rs/edu/raf/banka1/controller/MarketController.java
  market-service/src/main/java/rs/edu/raf/banka1/controller/OptionsController.java
  user-service/src/main/java/rs/edu/raf/banka1/configuration/SwaggerConfiguration.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/AuthenticationController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/CustomerController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/LoanController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/LoanRequestController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PaymentController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/PermissionController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/RecipientsController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransactionController.java
  user-service/src/main/java/rs/edu/raf/banka1/controller/TransferController.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/OrderMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarketOrder.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/OrderRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
Labels: lgtm, size/L, approved

#286 Add redis
  docker.compose.yaml
  market-service/pom.xml
  market-service/src/main/java/rs/edu/raf/banka1/configuration/AppConfig.java
  market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
  market-service/src/main/java/rs/edu/raf/banka1/model/ListingFuture.java
  market-service/src/main/java/rs/edu/raf/banka1/model/ListingHistory.java
  market-service/src/main/java/rs/edu/raf/banka1/model/ListingStock.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/CurrencyDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/ExchangeDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/InflationDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/OptionsDto.java
  market-service/src/main/java/rs/edu/raf/banka1/model/entities/Country.java
  market-service/src/main/java/rs/edu/raf/banka1/model/entities/Exchange.java
  market-service/src/main/java/rs/edu/raf/banka1/services/CurrencyService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ExchangeServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ForexServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/FuturesServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/InflationService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/ListingStockServiceImpl.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
  market-service/src/main/resources/examples/application.properties.example
Labels: lgtm, approved, size/M

#293 Sprint 9- physical and legal persons can create orders
  user-service/src/main/java/rs/edu/raf/banka1/controller/OrderController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/LegalOrderRequest.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/OrderMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarketOrder.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/OrderRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/scheduler/StockSimulationScheduler.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CustomerService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/OrderService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CustomerServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
  user-service/src/test/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJobTest.java
Labels: lgtm, size/L, approved

#299 Dockerfile update
  fetching-service/Dockerfile
Labels: lgtm, approved, size/XS

#295 Sprint 9
  user-service/src/main/java/rs/edu/raf/banka1/controller/ProfitController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CapitalDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/CapitalMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Capital.java
  user-service/src/main/java/rs/edu/raf/banka1/model/MarketOrder.java
  user-service/src/main/java/rs/edu/raf/banka1/model/StockProfit.java
  user-service/src/main/java/rs/edu/raf/banka1/repositories/StockProfitRepository.java
  user-service/src/main/java/rs/edu/raf/banka1/services/ProfitService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/ProfitServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/TransactionServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJob.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/ProfitServiceImplTest.java
Labels: lgtm, size/L, approved

#297 Kupovina opcija
  market-service/src/main/java/rs/edu/raf/banka1/controller/MarketController.java
  market-service/src/main/java/rs/edu/raf/banka1/repositories/OptionsRepository.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsService.java
  market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
  market-service/src/test/java/rs/edu/raf/banka1/services/OptionsServiceImplTest.java
  user-service/src/main/java/rs/edu/raf/banka1/services/MarketService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/MarketServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
Labels: lgtm, size/L, approved
