Repository RAF-SI-2023/Banka-1-Backend, pull requests merged in 2024-07, with the labels that each got.

#380 Prokic fix
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/otc_trade/BankOtcService.java
  user-service/src/test/java/rs/edu/raf/banka1/services/BankOtcServiceTest.java
Labels: lgtm, approved, size/XS

#381 Bootstrap change
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, size/S, approved

#382 testovi
  market-service/pom.xml
  market-service/src/main/java/rs/edu/raf/banka1/model/dtos/OptionsDto.java
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/banka1/controller/CapitalController.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CapitalServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/OrderServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/BankAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CapitalServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/TransactionServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarginAccountServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarginTransactionServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/MarketServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/OrderServiceImplTest.java
  user-service/src/test/java/rs/edu/raf/banka1/stocksimulation/StockSimulationJobTest.java
  user-service/src/test/java/rs/edu/raf/banka1/stocksimulation/StockSimulationTriggerTest.java
Labels: lgtm, approved, size/XXL

#383 Bootstrap my_stocks change
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/M

#385 tests for otc
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/otc_trade/BankOtcService.java
  user-service/src/test/java/rs/edu/raf/banka1/services/BankOtcServiceTest.java
Labels: lgtm, size/L, approved

#386 fix cards in user service
  user-service/src/main/java/rs/edu/raf/banka1/model/BankAccount.java
  user-service/src/main/java/rs/edu/raf/banka1/model/Card.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CardService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/BankAccountServiceImpl.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CardServiceImlp.java
  user-service/src/test/java/rs/edu/raf/banka1/services/CardServiceImplTest.java
Labels: lgtm, approved, size/M

#387 Sprint 9 order of services
  user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/M

#388 Sprint 9
  docker.compose.yaml.example
Labels: lgtm, size/L, approved

#389 company endpoint
  user-service/src/main/java/rs/edu/raf/banka1/controller/CompanyController.java
  user-service/src/main/java/rs/edu/raf/banka1/dtos/CompanyDto.java
  user-service/src/main/java/rs/edu/raf/banka1/mapper/TransferMapper.java
  user-service/src/main/java/rs/edu/raf/banka1/services/CompanyService.java
  user-service/src/main/java/rs/edu/raf/banka1/services/implementations/CompanyServiceImpl.java
  user-service/src/test/java/rs/edu/raf/banka1/services/implementations/CompanyServiceImplTest.java
Labels: lgtm, approved, size/M

#391 Random
  README.md
Labels: lgtm, approved, size/XS

#392 Sprint 9
  README.md
Labels: lgtm, size/L, approved, size/XS

#395 Sprint 9
  .prow/fetching-service.yaml
  .prow/market-service.yaml
  .prow/user-service.yaml
  README.md
Labels: lgtm, size/S, approved

#396 integracioni final
  docker-compose-test.yaml
  inittest.sql
  user-service/src/test/java/rs/edu/raf/banka1/cucumber/controller/UserControllerSteps.java
  user-service/src/test/resources/features/customer/customer_business_otc.feature
  user-service/src/test/resources/features/customer/customer_individual_otc.feature
  user-service/src/test/resources/features/customer/customer_whole_scenario.feature
  user-service/src/test/resources/features/employee/employee_whole_scenario.feature
Labels: lgtm, approved, size/XXL
